package:
  name: convex-qsr 
  version: '0.1.1'

build:
  number: 1

source:
  url: https://github.com/stephenshank/convex-qsr/archive/v0.1.1.tar.gz
  sha256: b1ec567ecd2565bf84d40a332127757ddedb33bf6bdc5b8007767b6ea944c021

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - numpy >=1.16.4
    - scipy >=1.1.0
    - pandas >=0.24.2
    - networkx >=2.3
    - flask >=1.1.1
    - biopython >=1.73
    - pysam >=0.15.2
test:
  commands:
    - cqsr_ec -h
  imports:
    - convex_qsr

about:
  home: https://github.com/stephenshank/convex-qsr
  license: MIT
  license_file: LICENSE
  summary: 'Reference guided quasispecies reconstruction using convex optimization'
